main: "com.tripixelstudios.highchrisben.characters.Main"
author: "Highchrisben"
version: "3.3.1"
name: "Characters"
description: "A plugin to create and manage visual player cards."
website: "http://tripixelstudios.com"

commands:
    character:
        description: "Basic character command."
        aliases: ["char"]
    travel:
        description: "Basic travel command."
        aliases: ["trav"]
    roll:
        description: "RollingCommand command."
    skill:
        description: "SkillsCommand command."